### PR TITLE
changed cohorts

### PR DESCRIPTION
**Pull request by denyskaduk**

### CODE REVIEW

**Comment by keesvanbochove** [comment]
Hi @denyskaduk I see you propose to merge an older commit with manual changes to the SQL definitions of some target cohorts into master, is this to re-apply those changes? It could work but in that case could you resolve the merge conflicts?

**Comment by denyskaduk** [comment]
HI, I'm on testing them now, how finish, will inform

**Comment by denyskaduk** [comment]
cohorts creation checked and fixed, was tested on synthetic data

**Comment by bdemeulder** [comment]
@keesvanbochove, can you review in lieu of Maxim?

**Comment by keesvanbochove** [comment]
@denyskaduk after setting episodetable to FALSE, it creates the first few cohorts but halts on cohort `105.sql`: 
```
5/70: Instantiation cohort [PIONEER T3.1] PCa high/intermediate risk conservative management  (105.sql)
  |===============================                                       |  44%Error: Error executing SQL:
org.postgresql.util.PSQLException: ERROR: syntax error at or near "======="
  Position: 3203
```
Looks like a remnant of a merge conflict that wasn't fully solved, could you check this?

**Comment by keesvanbochove** [comment]
OK, I've tested it against a Synthea database and both cohort diagnostics generation and runStudy work now, although I can't test everything because I'm not getting any target cohort counts in my synthetic data set. Also I will look into bumping CohortDiagnostics to v2.2 because I'm seeing a few issues there, but for now I think we should merge this into master.

**Pull request merged**
